"""
Institutional Kill-Switch Protocol v2.0
Bridges Live News Sentiment with Portfolio Drawdown Protection.
"""
import pandas as pd
import os

def check_live_signal():
    """Reads the signal generated by live_news_sentinel.py"""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    signal_path = os.path.join(base_dir, '..', 'results', 'live_risk_signal.txt')
    
    if os.path.exists(signal_path):
        with open(signal_path, 'r') as f:
            return f.read().strip()
    return "NORMAL"

def run_kill_switch_protocol():
    base_path = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(base_path, '..', 'data', 'volatile_regime_data.csv')
    
    # 1. GATE 1: LIVE GEOPOLITICAL CHECK
    current_signal = check_live_signal()
    print(f"\n--- 🛡️ RISK GATEWAY: LIVE SIGNAL IS {current_signal} ---")
    
    geopolitical_halt = False
    if current_signal == "CRITICAL":
        print("🚨 GEOPOLITICAL EMERGENCY: Live News Sentinel detected Extreme Risk.")
        print("FORCING SYSTEM-WIDE TRADING HALT.")
        geopolitical_halt = True

    # 2. GATE 2: HISTORICAL VOLATILITY CHECK
    try:
        df = pd.read_csv(data_path)
        
        # Define Kill-Switch Logic
        def apply_halt(row):
            # If news is CRITICAL or Regime is EXTREME, profit goes to 0 (No exposure)
            if geopolitical_halt or row['regime'] in ['EXTREME', 'OUTLIER']:
                return 0.0
            return row['profit_usd']

        df['mitigated_profit'] = df.apply(apply_halt, axis=1)
        
        # 3. AUDIT THE RESULTS
        original_mdd = df['profit_usd'].min()
        protected_mdd = df['mitigated_profit'].min()
        
        print("\n--- 🏁 EMERGENCY AUDIT REPORT ---")
        print(f"Max Potential Loss (Unprotected): ${original_mdd:,.2f}")
        print(f"Max Potential Loss (Protected):   ${protected_mdd:,.2f}")
        
        efficiency = ((original_mdd - protected_mdd) / original_mdd) * 100 if original_mdd != 0 else 0
        print(f"Risk Mitigation Efficiency:      {efficiency:.2f}%")
        
        # 4. EXPORT FOR DUBAI COMPLIANCE REVIEW
        results_path = os.path.join(base_path, '..', 'results', 'kill_switch_audit.csv')
        df.to_csv(results_path, index=False)
        print(f"\n✅ Institutional Audit saved: {results_path}")

    except Exception as e:
        print(f"❌ Kill-Switch Logic Error: {e}")

if __name__ == "__main__":
    run_kill_switch_protocol()